// ---------------------------------------------------------------------------
// One-off tool: emits raw SQL (schema migration + seed data) for pasting
// directly into a Turso SQL console, for cases where `npm run db:push` /
// `npm run db:seed` can't reach the database from the current machine.
//
// Usage: npx tsx scripts/export-migration-sql.ts > migration.sql
// ---------------------------------------------------------------------------
import { randomUUID } from "crypto";
import { brandData, MARKET_BY_SEGMENT, sample } from "../lib/db/seed-data";

function sqlString(value: string | number | boolean | null | undefined): string {
  if (value === null || value === undefined) return "NULL";
  if (typeof value === "boolean") return value ? "1" : "0";
  if (typeof value === "number") return String(value);
  return `'${value.replace(/'/g, "''")}'`;
}

function slugify(name: string): string {
  return name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");
}

const lines: string[] = [];

lines.push("-- Beauty Match: schema migration + seed data");
lines.push("-- Generated by scripts/export-migration-sql.ts — safe to run once against a fresh or pre-redesign database.");
lines.push("-- Paste this entire file into the Turso SQL console (or `turso db shell <db> < migration.sql`) and run it.");
lines.push("");

lines.push("-- ---- Schema migration: add new columns introduced by the premium redesign ----");
lines.push("ALTER TABLE brands ADD COLUMN segment TEXT;");
lines.push("ALTER TABLE brands ADD COLUMN origin_country TEXT;");
lines.push("ALTER TABLE brands ADD COLUMN cruelty_free INTEGER;");
lines.push("ALTER TABLE brands ADD COLUMN vegan INTEGER;");
lines.push("");
lines.push("ALTER TABLE products ADD COLUMN product_type TEXT;");
lines.push("ALTER TABLE products ADD COLUMN thumbnail_url TEXT;");
lines.push("ALTER TABLE products ADD COLUMN product_url TEXT;");
lines.push("ALTER TABLE products ADD COLUMN ingredient_percentages TEXT;");
lines.push("ALTER TABLE products ADD COLUMN benefits TEXT;");
lines.push("ALTER TABLE products ADD COLUMN texture TEXT;");
lines.push("ALTER TABLE products ADD COLUMN finish TEXT;");
lines.push("ALTER TABLE products ADD COLUMN fragrance TEXT;");
lines.push("ALTER TABLE products ADD COLUMN fragrance_free INTEGER;");
lines.push("ALTER TABLE products ADD COLUMN alcohol_free INTEGER;");
lines.push("ALTER TABLE products ADD COLUMN essential_oil_free INTEGER;");
lines.push("ALTER TABLE products ADD COLUMN cruelty_free INTEGER;");
lines.push("ALTER TABLE products ADD COLUMN vegan INTEGER;");
lines.push("ALTER TABLE products ADD COLUMN comedogenic_risk TEXT;");
lines.push("ALTER TABLE products ADD COLUMN sensitive_skin_friendly INTEGER;");
lines.push("ALTER TABLE products ADD COLUMN acne_friendly INTEGER;");
lines.push("ALTER TABLE products ADD COLUMN barrier_friendly INTEGER;");
lines.push("ALTER TABLE products ADD COLUMN pregnancy_safety_note TEXT;");
lines.push("ALTER TABLE products ADD COLUMN usage_frequency TEXT;");
lines.push("ALTER TABLE products ADD COLUMN morning_use INTEGER;");
lines.push("ALTER TABLE products ADD COLUMN night_use INTEGER;");
lines.push("ALTER TABLE products ADD COLUMN spf INTEGER;");
lines.push("ALTER TABLE products ADD COLUMN rating REAL;");
lines.push("ALTER TABLE products ADD COLUMN review_count INTEGER;");
lines.push("ALTER TABLE products ADD COLUMN tags TEXT;");
lines.push("ALTER TABLE products ADD COLUMN country TEXT;");
lines.push("ALTER TABLE products ADD COLUMN market TEXT;");
lines.push("ALTER TABLE products ADD COLUMN availability TEXT DEFAULT 'unknown';");
lines.push("ALTER TABLE products ADD COLUMN data_source TEXT DEFAULT 'admin';");
lines.push("");

lines.push("-- ---- Seed data: 28 brands, 54 products (development sample data, not verified real-world listings) ----");
lines.push("");

const brandIds: Record<string, string> = {};
for (const b of brandData) {
  const id = randomUUID();
  brandIds[b.name] = id;
  lines.push(
    `INSERT INTO brands (id, slug, name, tagline, segment, origin_country, status) VALUES (${sqlString(id)}, ${sqlString(slugify(b.name))}, ${sqlString(b.name)}, ${sqlString(b.tagline)}, ${sqlString(b.segment)}, ${sqlString(b.originCountry)}, 'live');`
  );
}

lines.push("");

for (const p of sample) {
  const brand = brandData.find((b) => b.name === p.brand)!;
  const marketInfo = MARKET_BY_SEGMENT[brand.segment];
  const id = randomUUID();
  const slug = `${slugify(p.name)}-${randomUUID().slice(0, 6)}`;

  const columns = [
    "id", "brand_id", "name", "slug", "category", "subcategory", "product_type",
    "price", "currency", "short_description", "full_description", "how_to_use",
    "key_ingredients", "benefits", "skin_types", "hair_types", "concerns", "cautions",
    "texture", "finish", "fragrance_free", "alcohol_free", "comedogenic_risk",
    "sensitive_skin_friendly", "acne_friendly", "barrier_friendly", "usage_frequency",
    "morning_use", "night_use", "spf", "tags", "country", "market", "availability",
    "data_source", "status",
  ];

  const values = [
    sqlString(id), sqlString(brandIds[p.brand]), sqlString(p.name), sqlString(slug),
    sqlString(p.category), sqlString(p.productType), sqlString(p.productType),
    sqlString(p.price), sqlString(marketInfo.currency), sqlString(p.shortDescription),
    sqlString(p.fullDescription), sqlString(p.howToUse),
    sqlString(JSON.stringify(p.keyIngredients ?? [])), sqlString(JSON.stringify(p.benefits ?? [])),
    sqlString(JSON.stringify(p.skinTypes ?? [])), sqlString(JSON.stringify(p.hairTypes ?? [])),
    sqlString(JSON.stringify(p.concerns ?? [])), sqlString(p.cautions ?? null),
    sqlString(p.texture ?? null), sqlString(p.finish ?? null),
    sqlString(p.fragranceFree ?? null), sqlString(p.alcoholFree ?? null), sqlString(p.comedogenicRisk ?? null),
    sqlString(p.sensitiveSkinFriendly ?? null), sqlString(p.acneFriendly ?? null), sqlString(p.barrierFriendly ?? null),
    sqlString(p.usageFrequency ?? null), sqlString(p.morningUse ?? null), sqlString(p.nightUse ?? null),
    sqlString(p.spf ?? null), sqlString(JSON.stringify(p.tags ?? [])), sqlString(JSON.stringify(marketInfo.country)),
    sqlString(marketInfo.market), sqlString("unknown"), sqlString("seed"), sqlString("live"),
  ];

  lines.push(`INSERT INTO products (${columns.join(", ")}) VALUES (${values.join(", ")});`);
}

lines.push("");
lines.push(`-- Done: ${brandData.length} brands, ${sample.length} products.`);

console.log(lines.join("\n"));
